### ISSUE TITLE
Remove tutorial assets from master branch

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#1]
It looks like some of the tutorial files made their way into the master branch with this commit: https://github.com/TwilioDevEd/account-verification-flask/commit/a6d595a00718274734b33457140c7defb9bac9a0

Please keep those files only in the `gh-pages` branch

**Comment by nebtrx** [comment]
Looks like something went wrong with the rebase, I'm working on it

**Comment by nebtrx** [comment]
Fixed
