### ISSUE TITLE
Use a .gitignore file from another Python project

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#12]
The `.gitignore` file in this repo has a lot of references to C# files that would never be part of a Python project.

I would copy over the `.gitignore` from https://github.com/TwilioDevEd/browser-calls-django/blob/master/.gitignore instead.

**Comment by nebtrx** [comment]
Ok.. I worked on the project from at some point using Python Tools for Visual Studio. It look like it add some lines to the .gitignore

**Comment by nebtrx** [comment]
Done!
