### ISSUE TITLE
Change config modules into config classes

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#2]
Python developers have unique expectations about when things should be in separate modules (files) and when they shouldn't.

For setting configuration variables across different environments, I prefer the class inheritance strategy laid out in the Flask docs: http://flask.pocoo.org/docs/0.10/config/#development-production

```
class Config(object):
    DEBUG = False
    TESTING = False
    DATABASE_URI = 'sqlite://:memory:'

class ProductionConfig(Config):
    DATABASE_URI = 'mysql://user@localhost/foo'

class DevelopmentConfig(Config):
    DEBUG = True

class TestingConfig(Config):
    TESTING = True
```

Here's a more detailed example from my favorite Flask repo: https://github.com/miguelgrinberg/flasky/blob/master/config.py

**Comment by nebtrx** [comment]
Perfect, no trouble. I'll move on this approach. I review a couple of approaches. I used this as a neutral one because in some people prefer the env var one. But personally I go for the class inheritance

**Comment by nebtrx** [comment]
Done!
