### ISSUE TITLE
Remove SQLALCHEMY_ECHO setting

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#3]
It's sometimes useful to see SQL queries in local development, but this is too much information for developers trying our app for the first time.

Please remove the `SQLALCHEMY_ECHO = True` line from the app config: https://github.com/TwilioDevEd/account-verification-flask/blob/master/account_verification_flask/config/defaults.py#L9

**Comment by nebtrx** [comment]
Ok, I'll fix it.
