### ISSUE TITLE
Remove runserver.py

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#4]
This project is already using the Flask-Script extension, which provides a built-in `runserver` command, so you don't need a separate module implementing it yourself.

Remove `runserver.py` and update the README to tell developers they can run the app with `python manage.py runserver`.

This new command also runs the Flask server on port 5000, which is the default port for Flask and a better choice than 5555.

**Comment by nebtrx** [comment]
Done!
