### ISSUE TITLE
Update the index.html template to say "Flask" instead of "Ruby on Rails"

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#5]
https://github.com/TwilioDevEd/account-verification-flask/blob/master/account_verification_flask/templates/index.html#L6 still says "Ruby on Rails" - please update it to say "Flask"

**Comment by nebtrx** [comment]
Ok thanks, I'll correct it

**Comment by nebtrx** [comment]
Fixed!
