### ISSUE TITLE
Update requirements.txt file

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#6]
Please update the `requirements.txt` file for this app to include the requirements necessary to run the tests.

You can just add the test requirements to the end of the file like this: https://github.com/TwilioDevEd/browser-calls-django/blob/master/requirements.txt#L17-L21

I think the ones you'll need are:

- `Flask-Testing`
- `coverage`
- `mock`

**Comment by nebtrx** [comment]
Ok..I thought I got them, I must loss them at some point, I got troubles installing Flask-Testing and it dependencies. Consider done!

**Comment by nebtrx** [comment]
Indeed, I had troubles with Flask-Testing, I reinstalled it an then just puff.. . Fixed!
