### ISSUE TITLE
Don't use `.new()` when instantiating a class

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#7]
You have a couple lines where you use your `AuthyServices` class in the views module:

```
AuthyServices.new().request_phone_confirmation_code(user)
```

Creating a new instance of the class every time you need to use it will look strange to most Python developers. Instead, create an instance of that class and use it in a separate line:

```
authy = AuthyServices()
authy.request_phone_confirmation_code(user)
```

You should also remove the `new()` staticmethod from all your classes:

```
    @staticmethod
    def new():
        return AuthyServices()
```

Python developers expect to instantiate classes by invoking them directly with `AuthyServices()`

**Comment by nebtrx** [comment]
Ok, thanks. My bad, I took it borrowed from Ruby.
