### ISSUE TITLE
Clean up comments, semicolons, trailing whitespace and read up on PEP8

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/account-verification-flask#8]
We should clean up this app's code a little before we show it to other developers. A few things I spotted:

- Commented out code ([like this](https://github.com/TwilioDevEd/account-verification-flask/blob/master/manage.py#L20)
- Unnecessary semicolons ([like here](https://github.com/TwilioDevEd/account-verification-flask/blob/master/account_verification_flask/models/models.py#L22)). Python rarely needs them
- Trailing whitespace ([here](https://github.com/TwilioDevEd/account-verification-flask/blob/master/account_verification_flask/views.py#L115))

I would also recommend installing a Python linter in your text editor or reading up on [PEP8](https://www.python.org/dev/peps/pep-0008/), the Python style guide. Python has strict conventions for how code should be formatted.

For example, [this line](https://github.com/TwilioDevEd/account-verification-flask/blob/master/account_verification_flask/views.py#L26):

```
if User.query.filter(User.email == form.email.data).count()>0 :
```

Should instead read like this:

```
if User.query.filter(User.email == form.email.data).count() > 0:
```

([here's the relevant section of PEP8](https://www.python.org/dev/peps/pep-0008/#other-recommendations))

**Comment by nebtrx** [comment]
Shame on me!!, I totally missed it and I freak out when I do code review to others and I see this. Fixed!
